[package]
name = "babyshusher3000"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
soloud = "1"
rand = "0.8.4"
rand_distr = "0.4.3"
